# Site
name: "IEEE Insight"
title: "Insight | IEEE"
description: "The official blog of IEEE Student Branch, NIT Durgapur. Inspired by Medium"
logo: "assets/images/front_banner.png"
big_logo: "assets/images/banner_big.png"
favicon: "assets/images/logo.png"
baseurl:
google_analytics: "UA-154066599-2"
disqus: "insightieee"
mailchimp-list: "https://github.us19.list-manage.com/subscribe?u=b7dcc89b774fb7b6ce34f29f9&id=c8b757bbd2"
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Arindam:
    name: Arindam
    display_name: Arindam Dutta
    avatar: "assets/images/arindam.jpg"
    description: ""
    member: "true"
  Amank:
    name: Amank
    display_name: Aman Kumar
    avatar: "assets/images/Aman_kumar.jpg"
    description: "Another engineer in the making. Loves to learn new things and most importantly, enjoying life!"
    member: "true"
  Aneek:
    name: Aneek
    display_name: Aneek Biswas
    avatar: "assets/images/Aneek2.jpg"
    description: "A Final year Civil Engineering undergraduate at NIT Durgapur with a keen interest in Structural Engineering and Concrete Technology"
    member: "false"
  Dayeeta:
    name: Dayeeta
    display_name: Dayeeta Pal
    avatar: "assets/images/Dayeeta.jpg"
    description: "A Final year MME undergraduate at NIT Durgapur with a keen interest in the field of biomaterials."
    member: "false"
  Anurag:
    name: Anurag
    display_name: Anurag Sarkar
    avatar: "assets/images/Anurag.jpg"
    description: "Biomedical Engineering Enthusiast, ML Enthusiast, NLP Enthusiast."
    member: "true"
  Payel:
    name: Payel
    display_name: Payel Bose
    avatar: "assets/images/payel.jpg"
    description: "A creative thinker and graphics designer. Hope to code with coffee one dayðŸ¤”"
    member: "true"
  Shubhangee:
    name: Shubhangee
    display_name: Shubhangee
    avatar: "assets/images/shubhangee.jpg"
    description: "Robo freak -interested in Robotics and automation."
    member: "true"
  Vimal:
    name: Vimal
    display_name: Vimal Dubey
    avatar: "assets/images/vimal.jpg"
    description: "Enthusiast in ML, Cloud Computing"
    member: "true"
  Ishaan:
    name: Ishaan
    display_name: Ishaan Sinha
    avatar: "assets/images/ishaan.jpeg"
    description: "Creative writer, reading enthusiast, blog researcher"
    member: "true"
  Disha:
    name: Disha
    display_name: Disha Sharma
    avatar: "assets/images/disha.jpg"
    description: "A creative writer and designer with on point sketching tricks."
    member: "true"
  Arka:
    name: Arka
    display_name: Arka Seth
    avatar: "assets/images/arka.jpg"
    description: "Technologist. Avid gamer and coder. Nerd maybe. Love to write. Interested in Machine Learning, Cryptography, and Web Development."
    member: "true"
  Tanujit:
    name: Tanujit
    display_name: Tanujit Ghosh
    avatar: "assets/images/tanujit.jpg"
    description: "Technologist.Gamer.Coder.Interested in web development,learning new technologies"
    member: "true"
  Soumya:
    name: Soumya
    display_name: Soumya Chatterjee
    avatar: "assets/images/soumya.jpg"
    description: "Mainly working on quantum communication and computing, also interested in cosmology and space science. "
    member: "true"
  Sagar:
    name: Sagar
    display_name: Sagar Agarwal
    avatar: "assets/images/sagar.jpeg"
    description: "An enthusiastic techie. Interested in Artificial Intelligence and Web Development. Love to learn more and more about technology. "
    member: "true"
  Akshat:
    name: Akshat
    display_name: Akshat Bhatnagar
    avatar: "assets/images/Akshat.jpg"
    description: "Love to play with technology and innovating new stuffs!"
    member: "true"
  Aman:
    name: Aman
    display_name: Aman Agarwal
    avatar: "assets/images/aman.jpg"
    description: "Amateur App Developer and designer."
    member: "true"
  Sayan:
    name: Sayan
    display_name: Sayan Mondal
    avatar: "assets/images/sayan.jpg"
    description: "Passionate about astrophysics."
    member: "true"
  Vaishali:
    name: Vaishali
    display_name: Vaishali Barua
    avatar: "assets/images/vaishali.jpg"
    description: "A tech enthusiast, learning designer, budding writer and a passionate basketball player."
    member: "true"
  Santam:
    name: Santam
    display_name: Santam Roy Choudhury
    avatar: "assets/images/santam.jpg"
    description: "A budding software developer and amateur night sky observer. Plan to make an atom bomb some dayðŸ˜‰."
    member: "true"
  Durbar:
    name: Durbar
    display_name: Durbar Chakrabarty
    avatar: "assets/images/2024/Durbar.jpeg"
    description: "Learner. Getting nerdier by the day. Interested in Artificial Intelligence, Quantum Computing and Web Development."
    member: "true"
  Nitin:
    name: Nitin
    display_name: Nitin Kushwaha
    avatar: "assets/images/2024/Nitin.jpg"
    description: "Tech-Savvy. Like innovation, problem solving, programming and development. Interested in AI."
    member: "true"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
